# Generated by Django 6.0.7 on 2026-07-18 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Contoh: BBCA, BTC, GOLD', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Contoh: Bank Central Asia, Bitcoin, Emas Antam', max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Saham'), ('CRYPTO', 'Cryptocurrency'), ('GOLD', 'Emas fisik')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, help_text='Menggunakan 8 desimal untuk akurasi Crypto', max_digits=20)),
                ('recorded_at', models.DateTimeField(help_text='Waktu pengambilan harga dari API pihak ke-3')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='assets.asset')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('asset', 'recorded_at')},
            },
        ),
    ]
