# Generated by Django 6.0.7 on 2026-07-18 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Beli'), ('SELL', 'Jual')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quantity', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolios', to='assets.asset')),
            ],
        ),
    ]
